// ----------------------------------------------------------------------

export const fullAddress = [
  'Thôn Đồng Bé, xã Hòa Tâm, huyện Đông Hòa, tỉnh Phú Yên',
  'Quốc lộ 1A, thị trấn Chí Thạnh, huyện Tuy An, tỉnh Phú Yên',
  'Xã Xuân Hòa Nam, huyện Đông Hòa, tỉnh Phú Yên',
];

export const country = [
  'Gành Đá Đĩa',
  'Hòn Yến',
  'Bãi Xép',
  'Hải đăng Mũi Điện',
  'Bãi Môn',
  'Đầm Ô Loan',
  'Vịnh Vũng Rô',
  'Đảo Nhất Tự Sơn',
  'Tháp Nhạn',
  'Tháp Nghinh Phong',
  'Đảo Hòn Nưa',
  'Núi Đá Bia',
  'Cambodia',
  'Virgin Islands, British',
  'Bahamas',
  'Italy',
  'France',
  'Portugal',
  'Nepal',
  'Saint Vincent and the Grenadines',
  'Greenland',
  'Maldives',
  'Comoros',
  'Bhutan',
  'Tuvalu',
  'Ethiopia',
  'Myanmar',
  'Libyan Arab Jamahiriya',
  'Senegal',
  'Malta',
  'Kyrgyz Republic',
  'Turks and Caicos Islands',
  'Gibraltar',
  'Sweden',
  'Zambia',
  'Isle of Man',
  'Canada',
  'Turkey',
  'Samoa',
  'Vietnam',
];
